name: Run on label set

on:
  pull_request:
    types: labeled


jobs:
  build:
    name: Wow!

    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2

      - name: greet
        run: echo "${{github.event.pull_request.head.sha}}"
