name: Run on label set

on: [pull_request]

jobs:
  build:
    name: Wow!

    runs-on: ubuntu-latest
    steps: 
      # Check-out repository
      - uses: actions/checkout@v2

      - name: greet
        run: echo "Hello ${INPUT_REF}"
        with:
          ref: helo
