name: Run on label set

on:
  pull_request:
    types: labeled


jobs:
  build:
    name: Wow!

    if: contains( github.event.pull_request.labels.*.name, 'No merge conflict')
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
      with:
        ref: "merge/${{github.base_ref}}/${{github.head_ref}}/${{github.event.pull_request.head.sha}}"

    - name: greet
      run: echo "${{github.event.pull_request.head.sha}}"
